### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by amir-arad** [daid/TinyCI#1]
I'm in the GH actions beta and I'd be happy to try it out if/when you have a setup example

**Comment by daid** [comment]
TinyCI has nothing to do with github actions (it actually predates the github actions announcement. And servered my need for something quick and simple)

There is are differences between TinyCI and github actions:

- TinyCI does not run sandboxed, no docker or anything.
- TinyCI keeps the last build results, and thus does incremental builds, while github actions does a full rebuild every time.


But it should be quite simple to change the .tinyci config:
https://github.com/daid/EmptyEpsilon/blob/master/.tinyci
Into an github actions config:
https://github.com/daid/SeriousProton2/blob/master/.github/workflows/main.yml


However, I do think it will burn trough minutes quite quick. So I put out a question about that:
https://github.community/t5/GitHub-Actions/Total-amount-of-minutes-used/m-p/30690/highlight/false

**Comment by daid** [comment]
I do have a pretty status page:
http://daid.eu/tinyci/
